"""Pydantic schema package."""

from app.schemas.auth_schema import AuthLoginRequest, AuthLoginResponse, AuthUserResponse
from app.schemas.attendance_schema import (
    AttendanceCreate,
    AttendanceResponse,
    AttendanceSummaryResponse,
    WorkOutputCreate,
    WorkOutputResponse,
)
from app.schemas.employee_schema import (
    EmployeeAddressResponse,
    EmployeeAssignmentResponse,
    EmployeeAttendanceSummary,
    EmployeeBpjsResponse,
    EmployeeContractResponse,
    EmployeeCreate,
    EmployeeDetailResponse,
    EmployeeDocumentCreate,
    EmployeeDocumentResponse,
    EmployeeFamilyCreate,
    EmployeeFamilyResponse,
    EmployeeIdentityCreate,
    EmployeeIdentityResponse,
    EmployeeListResponse,
    EmployeeMovementResponse,
    EmployeeMutationRequest,
    EmployeePayrollSummary,
    EmployeeProfileResponse,
    EmployeeStatusChangeRequest,
    EmployeeStatusResponse,
    EmployeeUpdate,
)
from app.schemas.reference_schema import ReferenceItemResponse

__all__ = [
    "AuthLoginRequest",
    "AuthLoginResponse",
    "AuthUserResponse",
    "AttendanceCreate",
    "AttendanceResponse",
    "AttendanceSummaryResponse",
    "EmployeeAddressResponse",
    "EmployeeAssignmentResponse",
    "EmployeeAttendanceSummary",
    "EmployeeBpjsResponse",
    "EmployeeContractResponse",
    "EmployeeCreate",
    "EmployeeDetailResponse",
    "EmployeeDocumentCreate",
    "EmployeeDocumentResponse",
    "EmployeeFamilyCreate",
    "EmployeeFamilyResponse",
    "EmployeeIdentityCreate",
    "EmployeeIdentityResponse",
    "EmployeeListResponse",
    "EmployeeMovementResponse",
    "EmployeeMutationRequest",
    "EmployeePayrollSummary",
    "EmployeeProfileResponse",
    "EmployeeStatusChangeRequest",
    "EmployeeStatusResponse",
    "EmployeeUpdate",
    "ReferenceItemResponse",
    "WorkOutputCreate",
    "WorkOutputResponse",
]
