#!/usr/bin/env python
"""Governance helpers for PT GBR HRIS imports and data quality."""

from __future__ import annotations

import csv
import hashlib
import json
import os
from pathlib import Path
from typing import Iterable

from dotenv import load_dotenv
from sqlalchemy import URL, bindparam, create_engine, text

PROJECT_ROOT = Path(__file__).resolve().parents[1]
load_dotenv(PROJECT_ROOT / ".env")

SOURCE_PERIOD = "Maret 2026"
REPORTS_DIR = PROJECT_ROOT / "reports"
DEFAULT_REPORT_PATH = REPORTS_DIR / "hris_data_quality_review_maret_2026.csv"


def _governance_tables_exist(connection) -> bool:
    return bool(
        connection.execute(
            text(
                """
                SELECT to_regclass('public.import_batches') IS NOT NULL
                   AND to_regclass('public.data_quality_issues') IS NOT NULL
                """
            )
        ).scalar()
    )


def _quote_identifier(value: str) -> str:
    return '"' + value.replace('"', '""') + '"'


def ensure_governance_tables(connection) -> None:
    if _governance_tables_exist(connection):
        return

    connection.execute(
        text(
            """
            CREATE TABLE IF NOT EXISTS import_batches (
                import_batch_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                source_period VARCHAR(32) NOT NULL,
                source_files JSONB NOT NULL DEFAULT '[]'::jsonb,
                files_checksum VARCHAR(128) NOT NULL,
                source_rows INTEGER NOT NULL DEFAULT 0,
                unique_rows INTEGER NOT NULL DEFAULT 0,
                imported_rows INTEGER NOT NULL DEFAULT 0,
                date_reviews INTEGER NOT NULL DEFAULT 0,
                status VARCHAR(24) NOT NULL DEFAULT 'SUCCESS',
                started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                finished_at TIMESTAMPTZ,
                notes TEXT
            )
            """
        )
    )
    connection.execute(
        text(
            """
            CREATE TABLE IF NOT EXISTS data_quality_issues (
                issue_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                issue_key VARCHAR(180) NOT NULL UNIQUE,
                issue_code VARCHAR(64) NOT NULL,
                severity VARCHAR(16) NOT NULL,
                status VARCHAR(16) NOT NULL DEFAULT 'OPEN',
                employee_id BIGINT REFERENCES employees(employee_id) ON DELETE SET NULL,
                source_period VARCHAR(32) NOT NULL,
                source_reference VARCHAR(255),
                observed_value TEXT,
                recommendation TEXT,
                first_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                resolved_at TIMESTAMPTZ,
                created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                CONSTRAINT ck_data_quality_issues_severity
                    CHECK (severity IN ('BLOCKING', 'REVIEW', 'INFO')),
                CONSTRAINT ck_data_quality_issues_status
                    CHECK (status IN ('OPEN', 'VERIFIED', 'FIXED', 'IGNORED'))
            )
            """
        )
    )
    for ddl in (
        "CREATE INDEX IF NOT EXISTS ix_import_batches_source_period ON import_batches(source_period)",
        "CREATE INDEX IF NOT EXISTS ix_import_batches_started_at ON import_batches(started_at)",
        "CREATE INDEX IF NOT EXISTS ix_data_quality_issues_status ON data_quality_issues(status)",
        "CREATE INDEX IF NOT EXISTS ix_data_quality_issues_severity ON data_quality_issues(severity)",
        "CREATE INDEX IF NOT EXISTS ix_data_quality_issues_employee_id ON data_quality_issues(employee_id)",
        "CREATE INDEX IF NOT EXISTS ix_data_quality_issues_source_period ON data_quality_issues(source_period)",
        "CREATE UNIQUE INDEX IF NOT EXISTS uq_employee_assignments_one_current ON employee_assignments(employee_id) WHERE is_current = true",
        "CREATE UNIQUE INDEX IF NOT EXISTS uq_employee_contracts_one_open ON employee_contracts(employee_id) WHERE end_date IS NULL",
        "CREATE UNIQUE INDEX IF NOT EXISTS uq_employee_identities_nik_number ON employee_identities(identity_number) WHERE upper(identity_type) IN ('NIK', 'KTP')",
    ):
        connection.execute(text(ddl))


def ensure_governance_tables_with_admin() -> None:
    admin_user = os.getenv("DB_ADMIN_USER", "").strip()
    admin_password = os.getenv("DB_ADMIN_PASSWORD", "").strip()
    app_user = os.getenv("DB_USER", "").strip()
    db_name = os.getenv("DB_NAME", "").strip()
    db_host = os.getenv("DB_HOST", "localhost").strip()
    db_port = int(os.getenv("DB_PORT", "5432").strip() or "5432")

    if not admin_user or not admin_password or not db_name:
        return

    admin_url = URL.create(
        drivername="postgresql+psycopg2",
        username=admin_user,
        password=admin_password,
        host=db_host,
        port=db_port,
        database=db_name,
    )
    admin_engine = create_engine(admin_url, pool_pre_ping=True, future=True)
    try:
        with admin_engine.begin() as connection:
            if not _governance_tables_exist(connection):
                connection.execute(
                    text(
                        """
                        CREATE TABLE IF NOT EXISTS import_batches (
                            import_batch_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            source_period VARCHAR(32) NOT NULL,
                            source_files JSONB NOT NULL DEFAULT '[]'::jsonb,
                            files_checksum VARCHAR(128) NOT NULL,
                            source_rows INTEGER NOT NULL DEFAULT 0,
                            unique_rows INTEGER NOT NULL DEFAULT 0,
                            imported_rows INTEGER NOT NULL DEFAULT 0,
                            date_reviews INTEGER NOT NULL DEFAULT 0,
                            status VARCHAR(24) NOT NULL DEFAULT 'SUCCESS',
                            started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                            finished_at TIMESTAMPTZ,
                            notes TEXT
                        )
                        """
                    )
                )
                connection.execute(
                    text(
                        """
                        CREATE TABLE IF NOT EXISTS data_quality_issues (
                            issue_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            issue_key VARCHAR(180) NOT NULL UNIQUE,
                            issue_code VARCHAR(64) NOT NULL,
                            severity VARCHAR(16) NOT NULL,
                            status VARCHAR(16) NOT NULL DEFAULT 'OPEN',
                            employee_id BIGINT REFERENCES employees(employee_id) ON DELETE SET NULL,
                            source_period VARCHAR(32) NOT NULL,
                            source_reference VARCHAR(255),
                            observed_value TEXT,
                            recommendation TEXT,
                            first_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                            last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                            resolved_at TIMESTAMPTZ,
                            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                            CONSTRAINT ck_data_quality_issues_severity
                                CHECK (severity IN ('BLOCKING', 'REVIEW', 'INFO')),
                            CONSTRAINT ck_data_quality_issues_status
                                CHECK (status IN ('OPEN', 'VERIFIED', 'FIXED', 'IGNORED'))
                        )
                        """
                    )
                )
            for ddl in (
                "CREATE INDEX IF NOT EXISTS ix_import_batches_source_period ON import_batches(source_period)",
                "CREATE INDEX IF NOT EXISTS ix_import_batches_started_at ON import_batches(started_at)",
                "CREATE INDEX IF NOT EXISTS ix_data_quality_issues_status ON data_quality_issues(status)",
                "CREATE INDEX IF NOT EXISTS ix_data_quality_issues_severity ON data_quality_issues(severity)",
                "CREATE INDEX IF NOT EXISTS ix_data_quality_issues_employee_id ON data_quality_issues(employee_id)",
                "CREATE INDEX IF NOT EXISTS ix_data_quality_issues_source_period ON data_quality_issues(source_period)",
                "CREATE UNIQUE INDEX IF NOT EXISTS uq_employee_assignments_one_current ON employee_assignments(employee_id) WHERE is_current = true",
                "CREATE UNIQUE INDEX IF NOT EXISTS uq_employee_contracts_one_open ON employee_contracts(employee_id) WHERE end_date IS NULL",
                "CREATE UNIQUE INDEX IF NOT EXISTS uq_employee_identities_nik_number ON employee_identities(identity_number) WHERE upper(identity_type) IN ('NIK', 'KTP')",
            ):
                connection.execute(text(ddl))
            if app_user:
                quoted_user = _quote_identifier(app_user)
                connection.execute(
                    text(
                        f"GRANT SELECT, INSERT, UPDATE, DELETE ON import_batches, data_quality_issues TO {quoted_user}"
                    )
                )
                connection.execute(
                    text(
                        f"GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO {quoted_user}"
                    )
                )
    finally:
        admin_engine.dispose()


def calculate_files_checksum(paths: Iterable[Path]) -> str:
    digest = hashlib.sha256()
    for path in sorted(paths, key=lambda item: item.name.lower()):
        digest.update(path.name.encode("utf-8"))
        digest.update(str(path.stat().st_size).encode("ascii"))
        with path.open("rb") as file_obj:
            for chunk in iter(lambda: file_obj.read(1024 * 1024), b""):
                digest.update(chunk)
    return digest.hexdigest()


def record_import_batch(
    connection,
    *,
    source_files: Iterable[Path],
    source_rows: int,
    unique_rows: int,
    imported_rows: int,
    date_reviews: int,
    status: str = "SUCCESS",
    notes: str | None = None,
    source_period: str = SOURCE_PERIOD,
) -> int:
    ensure_governance_tables(connection)
    file_paths = list(source_files)
    payload = [
        {
            "name": path.name,
            "path": str(path),
            "size": path.stat().st_size,
        }
        for path in file_paths
    ]
    return int(
        connection.execute(
            text(
                """
                INSERT INTO import_batches (
                    source_period, source_files, files_checksum, source_rows,
                    unique_rows, imported_rows, date_reviews, status, finished_at, notes
                )
                VALUES (
                    :source_period, CAST(:source_files AS jsonb), :files_checksum,
                    :source_rows, :unique_rows, :imported_rows, :date_reviews,
                    :status, now(), :notes
                )
                RETURNING import_batch_id
                """
            ),
            {
                "source_period": source_period,
                "source_files": json.dumps(payload),
                "files_checksum": calculate_files_checksum(file_paths),
                "source_rows": source_rows,
                "unique_rows": unique_rows,
                "imported_rows": imported_rows,
                "date_reviews": date_reviews,
                "status": status,
                "notes": notes,
            },
        ).scalar_one()
    )


ISSUE_QUERIES: tuple[tuple[str, str, str, str, str], ...] = (
    (
        "MISSING_ASSIGNMENT",
        "BLOCKING",
        "Aktif tanpa assignment current.",
        "Lengkapi assignment aktif sebelum data dipakai untuk kontrol manpower.",
        """
        SELECT e.employee_id, NULL::text AS observed_value, 'employees' AS source_reference
        FROM employees e
        WHERE e.is_active = true
          AND NOT EXISTS (
              SELECT 1
              FROM employee_assignments a
              WHERE a.employee_id = e.employee_id
                AND a.is_current = true
          )
        """,
    ),
    (
        "DUPLICATE_CURRENT_ASSIGNMENT",
        "BLOCKING",
        "Assignment current ganda.",
        "Tutup assignment lama dan sisakan satu assignment aktif.",
        """
        SELECT employee_id, COUNT(*)::text AS observed_value, 'employee_assignments' AS source_reference
        FROM employee_assignments
        WHERE is_current = true
        GROUP BY employee_id
        HAVING COUNT(*) > 1
        """,
    ),
    (
        "MULTIPLE_OPEN_CONTRACTS",
        "BLOCKING",
        "Kontrak terbuka ganda.",
        "Tutup kontrak lama dan sisakan satu kontrak terbuka.",
        """
        SELECT employee_id, COUNT(*)::text AS observed_value, 'employee_contracts' AS source_reference
        FROM employee_contracts
        WHERE end_date IS NULL
        GROUP BY employee_id
        HAVING COUNT(*) > 1
        """,
    ),
    (
        "DUPLICATE_EMPLOYEE_NO",
        "BLOCKING",
        "Nomor karyawan duplikat.",
        "Nomor karyawan harus unik.",
        """
        SELECT e.employee_id, e.employee_no AS observed_value, 'employees' AS source_reference
        FROM employees e
        WHERE e.employee_no IN (
            SELECT employee_no
            FROM employees
            GROUP BY employee_no
            HAVING COUNT(*) > 1
        )
        """,
    ),
    (
        "DUPLICATE_IDENTITY",
        "BLOCKING",
        "Nomor identitas duplikat.",
        "Verifikasi dokumen KTP/NIK dan sisakan satu pemilik identitas yang benar.",
        """
        SELECT i.employee_id, 'masked' AS observed_value, 'employee_identities' AS source_reference
        FROM employee_identities i
        WHERE i.identity_number IN (
            SELECT identity_number
            FROM employee_identities
            GROUP BY identity_number
            HAVING COUNT(*) > 1
        )
        """,
    ),
    (
        "FUTURE_ASSIGNMENT_START",
        "BLOCKING",
        "Tanggal aktif assignment berada di masa depan.",
        "Normalisasi ke tanggal snapshot atau koreksi tanggal masuk sesuai dokumen sumber.",
        """
        SELECT employee_id, start_date::text AS observed_value, 'employee_assignments' AS source_reference
        FROM employee_assignments
        WHERE is_current = true
          AND start_date > CURRENT_DATE
        """,
    ),
    (
        "FUTURE_STATUS_EFFECTIVE",
        "BLOCKING",
        "Tanggal efektif status berada di masa depan.",
        "Normalisasi status efektif ke tanggal snapshot atau koreksi tanggal sumber.",
        """
        SELECT employee_id, effective_date::text AS observed_value, 'employee_status_histories' AS source_reference
        FROM employee_status_histories
        WHERE effective_date > CURRENT_DATE
        """,
    ),
    (
        "FUTURE_CONTRACT_START",
        "BLOCKING",
        "Tanggal mulai kontrak berada di masa depan.",
        "Normalisasi kontrak ke tanggal snapshot atau koreksi tanggal sumber.",
        """
        SELECT employee_id, start_date::text AS observed_value, 'employee_contracts' AS source_reference
        FROM employee_contracts
        WHERE start_date > CURRENT_DATE
        """,
    ),
    (
        "SOURCE_DATE_REVIEW",
        "REVIEW",
        "Tanggal sumber dinormalisasi ke tanggal snapshot.",
        "Verifikasi tanggal asli pada file sumber HR.",
        """
        SELECT
            employee_id,
            CONCAT(
                'active_start=', start_date::text,
                '; original_join=',
                COALESCE(substring(notes from 'review_original_join_date=([0-9-]+)'), '-')
            ) AS observed_value,
            'employee_assignments.notes' AS source_reference
        FROM employee_assignments
        WHERE notes LIKE '%review_original_join_date=%'
        """,
    ),
    (
        "AGE_REVIEW",
        "REVIEW",
        "Usia aktif perlu verifikasi.",
        "Verifikasi ulang tanggal lahir di dokumen HR resmi.",
        """
        SELECT
            employee_id,
            CONCAT(birth_date::text, ' / ', EXTRACT(YEAR FROM age(CURRENT_DATE, birth_date))::int, ' tahun') AS observed_value,
            'employees.birth_date' AS source_reference
        FROM employees
        WHERE is_active = true
          AND birth_date IS NOT NULL
          AND (
              birth_date > CURRENT_DATE - INTERVAL '17 years'
              OR birth_date < CURRENT_DATE - INTERVAL '70 years'
          )
        """,
    ),
    (
        "MISSING_IDENTITY",
        "INFO",
        "Aktif tanpa nomor identitas.",
        "Lengkapi KTP/NIK jika tersedia di dokumen HR.",
        """
        SELECT e.employee_id, NULL::text AS observed_value, 'employee_identities' AS source_reference
        FROM employees e
        WHERE e.is_active = true
          AND NOT EXISTS (
              SELECT 1 FROM employee_identities i
              WHERE i.employee_id = e.employee_id
          )
        """,
    ),
    (
        "MISSING_ADDRESS",
        "INFO",
        "Aktif tanpa alamat.",
        "Lengkapi alamat domisili jika tersedia di dokumen HR.",
        """
        SELECT e.employee_id, NULL::text AS observed_value, 'employee_addresses' AS source_reference
        FROM employees e
        WHERE e.is_active = true
          AND NOT EXISTS (
              SELECT 1 FROM employee_addresses a
              WHERE a.employee_id = e.employee_id
          )
        """,
    ),
)


def _issue_key(issue_code: str, employee_id: int | None, observed_value: str | None) -> str:
    raw_value = f"{issue_code}|{employee_id or 'none'}|{observed_value or ''}"
    suffix = hashlib.sha1(raw_value.encode("utf-8")).hexdigest()[:16]
    return f"{issue_code}:{employee_id or 'none'}:{suffix}"


def build_current_issue_rows(connection, *, source_period: str = SOURCE_PERIOD) -> list[dict[str, object]]:
    rows: list[dict[str, object]] = []
    for issue_code, severity, description, recommendation, sql in ISSUE_QUERIES:
        for row in connection.execute(text(sql)).mappings():
            employee_id = row.get("employee_id")
            observed_value = row.get("observed_value")
            rows.append(
                {
                    "issue_key": _issue_key(
                        issue_code,
                        int(employee_id) if employee_id is not None else None,
                        str(observed_value) if observed_value is not None else None,
                    ),
                    "issue_code": issue_code,
                    "severity": severity,
                    "employee_id": employee_id,
                    "source_period": source_period,
                    "source_reference": row.get("source_reference"),
                    "observed_value": observed_value or description,
                    "recommendation": recommendation,
                }
            )
    return rows


def sync_data_quality_issues(connection, *, source_period: str = SOURCE_PERIOD) -> dict[str, int]:
    ensure_governance_tables(connection)
    rows = build_current_issue_rows(connection, source_period=source_period)
    current_keys = [str(row["issue_key"]) for row in rows]
    upserted = 0

    for row in rows:
        connection.execute(
            text(
                """
                INSERT INTO data_quality_issues (
                    issue_key, issue_code, severity, status, employee_id,
                    source_period, source_reference, observed_value, recommendation,
                    first_seen_at, last_seen_at, resolved_at
                )
                VALUES (
                    :issue_key, :issue_code, :severity, 'OPEN', :employee_id,
                    :source_period, :source_reference, :observed_value, :recommendation,
                    now(), now(), NULL
                )
                ON CONFLICT (issue_key) DO UPDATE
                SET issue_code = EXCLUDED.issue_code,
                    severity = EXCLUDED.severity,
                    employee_id = EXCLUDED.employee_id,
                    source_period = EXCLUDED.source_period,
                    source_reference = EXCLUDED.source_reference,
                    observed_value = EXCLUDED.observed_value,
                    recommendation = EXCLUDED.recommendation,
                    status = CASE
                        WHEN data_quality_issues.status = 'FIXED' THEN 'OPEN'
                        ELSE data_quality_issues.status
                    END,
                    last_seen_at = now(),
                    resolved_at = CASE
                        WHEN data_quality_issues.status = 'FIXED' THEN NULL
                        ELSE data_quality_issues.resolved_at
                    END,
                    updated_at = now()
                """
            ),
            row,
        )
        upserted += 1

    if current_keys:
        fixed = connection.execute(
            text(
                """
                UPDATE data_quality_issues
                SET status = 'FIXED',
                    resolved_at = now(),
                    updated_at = now()
                WHERE source_period = :source_period
                  AND status IN ('OPEN', 'VERIFIED')
                  AND issue_key NOT IN :issue_keys
                """
            ).bindparams(bindparam("issue_keys", expanding=True)),
            {"source_period": source_period, "issue_keys": current_keys},
        ).rowcount
    else:
        fixed = connection.execute(
            text(
                """
                UPDATE data_quality_issues
                SET status = 'FIXED',
                    resolved_at = now(),
                    updated_at = now()
                WHERE source_period = :source_period
                  AND status IN ('OPEN', 'VERIFIED')
                """
            ),
            {"source_period": source_period},
        ).rowcount

    counts = get_issue_counts(connection, source_period=source_period)
    return {
        "upserted": upserted,
        "fixed": int(fixed or 0),
        **counts,
    }


def get_issue_counts(connection, *, source_period: str = SOURCE_PERIOD) -> dict[str, int]:
    ensure_governance_tables(connection)
    rows = connection.execute(
        text(
            """
            SELECT severity, COUNT(*) AS total
            FROM data_quality_issues
            WHERE source_period = :source_period
              AND status = 'OPEN'
            GROUP BY severity
            """
        ),
        {"source_period": source_period},
    ).all()
    counts = {"open_blocking": 0, "open_review": 0, "open_info": 0}
    for severity, total in rows:
        key = f"open_{str(severity).lower()}"
        if key in counts:
            counts[key] = int(total or 0)
    counts["open_total"] = counts["open_blocking"] + counts["open_review"] + counts["open_info"]
    counts["watch_total"] = counts["open_blocking"] + counts["open_review"]
    return counts


def export_review_csv(connection, output_path: Path = DEFAULT_REPORT_PATH, *, source_period: str = SOURCE_PERIOD) -> int:
    ensure_governance_tables(connection)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    rows = connection.execute(
        text(
            """
            SELECT
                i.issue_code,
                i.severity,
                i.status,
                e.employee_id,
                e.employee_no,
                e.full_name,
                COALESCE(d.division_name, '-') AS current_division,
                COALESCE(p.position_name, '-') AS current_position,
                COALESCE(i.observed_value, '-') AS observed_value,
                COALESCE(i.recommendation, '-') AS recommendation
            FROM data_quality_issues i
            LEFT JOIN employees e ON e.employee_id = i.employee_id
            LEFT JOIN employee_assignments a ON a.employee_id = e.employee_id AND a.is_current = true
            LEFT JOIN divisions d ON d.division_id = a.division_id
            LEFT JOIN positions p ON p.position_id = a.position_id
            WHERE i.source_period = :source_period
              AND i.status IN ('OPEN', 'VERIFIED', 'IGNORED')
            ORDER BY
                CASE i.severity
                    WHEN 'BLOCKING' THEN 1
                    WHEN 'REVIEW' THEN 2
                    ELSE 3
                END,
                i.issue_code,
                d.division_name,
                e.employee_no
            """
        ),
        {"source_period": source_period},
    ).mappings().all()

    fieldnames = [
        "issue_code",
        "severity",
        "status",
        "employee_id",
        "employee_no",
        "full_name",
        "current_division",
        "current_position",
        "observed_value",
        "recommendation",
    ]
    with output_path.open("w", newline="", encoding="utf-8-sig") as csv_file:
        writer = csv.DictWriter(csv_file, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(dict(row) for row in rows)
    return len(rows)
